/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppReceptionRouteImport } from './routes/_app.reception'
import { Route as AppDoctorRouteImport } from './routes/_app.doctor'
import { Route as AppAppointmentsRouteImport } from './routes/_app.appointments'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppReceptionRoute = AppReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorRoute = AppDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/appointments': typeof AppAppointmentsRoute
  '/doctor': typeof AppDoctorRoute
  '/reception': typeof AppReceptionRoute
}
export interface FileRoutesByTo {
  '/appointments': typeof AppAppointmentsRoute
  '/doctor': typeof AppDoctorRoute
  '/reception': typeof AppReceptionRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/appointments': typeof AppAppointmentsRoute
  '/_app/doctor': typeof AppDoctorRoute
  '/_app/reception': typeof AppReceptionRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/appointments' | '/doctor' | '/reception'
  fileRoutesByTo: FileRoutesByTo
  to: '/appointments' | '/doctor' | '/reception' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/appointments'
    | '/_app/doctor'
    | '/_app/reception'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reception': {
      id: '/_app/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof AppReceptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctor': {
      id: '/_app/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AppDoctorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments': {
      id: '/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppDoctorRoute: typeof AppDoctorRoute
  AppReceptionRoute: typeof AppReceptionRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppDoctorRoute: AppDoctorRoute,
  AppReceptionRoute: AppReceptionRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
