/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWhitelabelRouteImport } from './routes/_app.whitelabel'
import { Route as AppTelemedicineRouteImport } from './routes/_app.telemedicine'
import { Route as AppSubscriptionsRouteImport } from './routes/_app.subscriptions'
import { Route as AppReceptionRouteImport } from './routes/_app.reception'
import { Route as AppRbacRouteImport } from './routes/_app.rbac'
import { Route as AppPharmacyRouteImport } from './routes/_app.pharmacy'
import { Route as AppPatientWidgetRouteImport } from './routes/_app.patient-widget'
import { Route as AppPatientOnboardingRouteImport } from './routes/_app.patient-onboarding'
import { Route as AppPatientRouteImport } from './routes/_app.patient'
import { Route as AppLabRouteImport } from './routes/_app.lab'
import { Route as AppEmrRouteImport } from './routes/_app.emr'
import { Route as AppDoctorRouteImport } from './routes/_app.doctor'
import { Route as AppClinicsRouteImport } from './routes/_app.clinics'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppAppointmentsRouteImport } from './routes/_app.appointments'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppPatientProfilePatientIdRouteImport } from './routes/_app.patient-profile.$patientId'
import { Route as AppAiScribeRouteImport } from './routes/_app.ai.scribe'
import { Route as AppAiRiskRouteImport } from './routes/_app.ai.risk'
import { Route as AppAiReportsRouteImport } from './routes/_app.ai.reports'
import { Route as AppAiReceptionistRouteImport } from './routes/_app.ai.receptionist'
import { Route as AppAiCopilotRouteImport } from './routes/_app.ai.copilot'
import { Route as AppAiCareRouteImport } from './routes/_app.ai.care'
import { Route as AppAdminSuperRouteImport } from './routes/_app.admin.super'
import { Route as AppAdminOrgRouteImport } from './routes/_app.admin.org'
import { Route as AppAdminFeaturesRouteImport } from './routes/_app.admin.features'
import { Route as AppAdminClinicRouteImport } from './routes/_app.admin.clinic'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWhitelabelRoute = AppWhitelabelRouteImport.update({
  id: '/whitelabel',
  path: '/whitelabel',
  getParentRoute: () => AppRoute,
} as any)
const AppTelemedicineRoute = AppTelemedicineRouteImport.update({
  id: '/telemedicine',
  path: '/telemedicine',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsRoute = AppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppReceptionRoute = AppReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => AppRoute,
} as any)
const AppRbacRoute = AppRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => AppRoute,
} as any)
const AppPharmacyRoute = AppPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientWidgetRoute = AppPatientWidgetRouteImport.update({
  id: '/patient-widget',
  path: '/patient-widget',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientOnboardingRoute = AppPatientOnboardingRouteImport.update({
  id: '/patient-onboarding',
  path: '/patient-onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientRoute = AppPatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => AppRoute,
} as any)
const AppLabRoute = AppLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AppRoute,
} as any)
const AppEmrRoute = AppEmrRouteImport.update({
  id: '/emr',
  path: '/emr',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorRoute = AppDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicsRoute = AppClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientProfilePatientIdRoute =
  AppPatientProfilePatientIdRouteImport.update({
    id: '/patient-profile/$patientId',
    path: '/patient-profile/$patientId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAiScribeRoute = AppAiScribeRouteImport.update({
  id: '/ai/scribe',
  path: '/ai/scribe',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRiskRoute = AppAiRiskRouteImport.update({
  id: '/ai/risk',
  path: '/ai/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppAiReportsRoute = AppAiReportsRouteImport.update({
  id: '/ai/reports',
  path: '/ai/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAiReceptionistRoute = AppAiReceptionistRouteImport.update({
  id: '/ai/receptionist',
  path: '/ai/receptionist',
  getParentRoute: () => AppRoute,
} as any)
const AppAiCopilotRoute = AppAiCopilotRouteImport.update({
  id: '/ai/copilot',
  path: '/ai/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppAiCareRoute = AppAiCareRouteImport.update({
  id: '/ai/care',
  path: '/ai/care',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSuperRoute = AppAdminSuperRouteImport.update({
  id: '/admin/super',
  path: '/admin/super',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOrgRoute = AppAdminOrgRouteImport.update({
  id: '/admin/org',
  path: '/admin/org',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminFeaturesRoute = AppAdminFeaturesRouteImport.update({
  id: '/admin/features',
  path: '/admin/features',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminClinicRoute = AppAdminClinicRouteImport.update({
  id: '/admin/clinic',
  path: '/admin/clinic',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/appointments': typeof AppAppointmentsRoute
  '/billing': typeof AppBillingRoute
  '/clinics': typeof AppClinicsRoute
  '/doctor': typeof AppDoctorRoute
  '/emr': typeof AppEmrRoute
  '/lab': typeof AppLabRoute
  '/patient': typeof AppPatientRoute
  '/patient-onboarding': typeof AppPatientOnboardingRoute
  '/patient-widget': typeof AppPatientWidgetRoute
  '/pharmacy': typeof AppPharmacyRoute
  '/rbac': typeof AppRbacRoute
  '/reception': typeof AppReceptionRoute
  '/subscriptions': typeof AppSubscriptionsRoute
  '/telemedicine': typeof AppTelemedicineRoute
  '/whitelabel': typeof AppWhitelabelRoute
  '/admin/clinic': typeof AppAdminClinicRoute
  '/admin/features': typeof AppAdminFeaturesRoute
  '/admin/org': typeof AppAdminOrgRoute
  '/admin/super': typeof AppAdminSuperRoute
  '/ai/care': typeof AppAiCareRoute
  '/ai/copilot': typeof AppAiCopilotRoute
  '/ai/receptionist': typeof AppAiReceptionistRoute
  '/ai/reports': typeof AppAiReportsRoute
  '/ai/risk': typeof AppAiRiskRoute
  '/ai/scribe': typeof AppAiScribeRoute
  '/patient-profile/$patientId': typeof AppPatientProfilePatientIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/appointments': typeof AppAppointmentsRoute
  '/billing': typeof AppBillingRoute
  '/clinics': typeof AppClinicsRoute
  '/doctor': typeof AppDoctorRoute
  '/emr': typeof AppEmrRoute
  '/lab': typeof AppLabRoute
  '/patient': typeof AppPatientRoute
  '/patient-onboarding': typeof AppPatientOnboardingRoute
  '/patient-widget': typeof AppPatientWidgetRoute
  '/pharmacy': typeof AppPharmacyRoute
  '/rbac': typeof AppRbacRoute
  '/reception': typeof AppReceptionRoute
  '/subscriptions': typeof AppSubscriptionsRoute
  '/telemedicine': typeof AppTelemedicineRoute
  '/whitelabel': typeof AppWhitelabelRoute
  '/': typeof AppIndexRoute
  '/admin/clinic': typeof AppAdminClinicRoute
  '/admin/features': typeof AppAdminFeaturesRoute
  '/admin/org': typeof AppAdminOrgRoute
  '/admin/super': typeof AppAdminSuperRoute
  '/ai/care': typeof AppAiCareRoute
  '/ai/copilot': typeof AppAiCopilotRoute
  '/ai/receptionist': typeof AppAiReceptionistRoute
  '/ai/reports': typeof AppAiReportsRoute
  '/ai/risk': typeof AppAiRiskRoute
  '/ai/scribe': typeof AppAiScribeRoute
  '/patient-profile/$patientId': typeof AppPatientProfilePatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/appointments': typeof AppAppointmentsRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/clinics': typeof AppClinicsRoute
  '/_app/doctor': typeof AppDoctorRoute
  '/_app/emr': typeof AppEmrRoute
  '/_app/lab': typeof AppLabRoute
  '/_app/patient': typeof AppPatientRoute
  '/_app/patient-onboarding': typeof AppPatientOnboardingRoute
  '/_app/patient-widget': typeof AppPatientWidgetRoute
  '/_app/pharmacy': typeof AppPharmacyRoute
  '/_app/rbac': typeof AppRbacRoute
  '/_app/reception': typeof AppReceptionRoute
  '/_app/subscriptions': typeof AppSubscriptionsRoute
  '/_app/telemedicine': typeof AppTelemedicineRoute
  '/_app/whitelabel': typeof AppWhitelabelRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/clinic': typeof AppAdminClinicRoute
  '/_app/admin/features': typeof AppAdminFeaturesRoute
  '/_app/admin/org': typeof AppAdminOrgRoute
  '/_app/admin/super': typeof AppAdminSuperRoute
  '/_app/ai/care': typeof AppAiCareRoute
  '/_app/ai/copilot': typeof AppAiCopilotRoute
  '/_app/ai/receptionist': typeof AppAiReceptionistRoute
  '/_app/ai/reports': typeof AppAiReportsRoute
  '/_app/ai/risk': typeof AppAiRiskRoute
  '/_app/ai/scribe': typeof AppAiScribeRoute
  '/_app/patient-profile/$patientId': typeof AppPatientProfilePatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/appointments'
    | '/billing'
    | '/clinics'
    | '/doctor'
    | '/emr'
    | '/lab'
    | '/patient'
    | '/patient-onboarding'
    | '/patient-widget'
    | '/pharmacy'
    | '/rbac'
    | '/reception'
    | '/subscriptions'
    | '/telemedicine'
    | '/whitelabel'
    | '/admin/clinic'
    | '/admin/features'
    | '/admin/org'
    | '/admin/super'
    | '/ai/care'
    | '/ai/copilot'
    | '/ai/receptionist'
    | '/ai/reports'
    | '/ai/risk'
    | '/ai/scribe'
    | '/patient-profile/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analytics'
    | '/appointments'
    | '/billing'
    | '/clinics'
    | '/doctor'
    | '/emr'
    | '/lab'
    | '/patient'
    | '/patient-onboarding'
    | '/patient-widget'
    | '/pharmacy'
    | '/rbac'
    | '/reception'
    | '/subscriptions'
    | '/telemedicine'
    | '/whitelabel'
    | '/'
    | '/admin/clinic'
    | '/admin/features'
    | '/admin/org'
    | '/admin/super'
    | '/ai/care'
    | '/ai/copilot'
    | '/ai/receptionist'
    | '/ai/reports'
    | '/ai/risk'
    | '/ai/scribe'
    | '/patient-profile/$patientId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/analytics'
    | '/_app/appointments'
    | '/_app/billing'
    | '/_app/clinics'
    | '/_app/doctor'
    | '/_app/emr'
    | '/_app/lab'
    | '/_app/patient'
    | '/_app/patient-onboarding'
    | '/_app/patient-widget'
    | '/_app/pharmacy'
    | '/_app/rbac'
    | '/_app/reception'
    | '/_app/subscriptions'
    | '/_app/telemedicine'
    | '/_app/whitelabel'
    | '/_app/'
    | '/_app/admin/clinic'
    | '/_app/admin/features'
    | '/_app/admin/org'
    | '/_app/admin/super'
    | '/_app/ai/care'
    | '/_app/ai/copilot'
    | '/_app/ai/receptionist'
    | '/_app/ai/reports'
    | '/_app/ai/risk'
    | '/_app/ai/scribe'
    | '/_app/patient-profile/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/whitelabel': {
      id: '/_app/whitelabel'
      path: '/whitelabel'
      fullPath: '/whitelabel'
      preLoaderRoute: typeof AppWhitelabelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/telemedicine': {
      id: '/_app/telemedicine'
      path: '/telemedicine'
      fullPath: '/telemedicine'
      preLoaderRoute: typeof AppTelemedicineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscriptions': {
      id: '/_app/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AppSubscriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reception': {
      id: '/_app/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof AppReceptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rbac': {
      id: '/_app/rbac'
      path: '/rbac'
      fullPath: '/rbac'
      preLoaderRoute: typeof AppRbacRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pharmacy': {
      id: '/_app/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AppPharmacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patient-widget': {
      id: '/_app/patient-widget'
      path: '/patient-widget'
      fullPath: '/patient-widget'
      preLoaderRoute: typeof AppPatientWidgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patient-onboarding': {
      id: '/_app/patient-onboarding'
      path: '/patient-onboarding'
      fullPath: '/patient-onboarding'
      preLoaderRoute: typeof AppPatientOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patient': {
      id: '/_app/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof AppPatientRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lab': {
      id: '/_app/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof AppLabRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/emr': {
      id: '/_app/emr'
      path: '/emr'
      fullPath: '/emr'
      preLoaderRoute: typeof AppEmrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctor': {
      id: '/_app/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AppDoctorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clinics': {
      id: '/_app/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof AppClinicsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments': {
      id: '/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patient-profile/$patientId': {
      id: '/_app/patient-profile/$patientId'
      path: '/patient-profile/$patientId'
      fullPath: '/patient-profile/$patientId'
      preLoaderRoute: typeof AppPatientProfilePatientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/scribe': {
      id: '/_app/ai/scribe'
      path: '/ai/scribe'
      fullPath: '/ai/scribe'
      preLoaderRoute: typeof AppAiScribeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/risk': {
      id: '/_app/ai/risk'
      path: '/ai/risk'
      fullPath: '/ai/risk'
      preLoaderRoute: typeof AppAiRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/reports': {
      id: '/_app/ai/reports'
      path: '/ai/reports'
      fullPath: '/ai/reports'
      preLoaderRoute: typeof AppAiReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/receptionist': {
      id: '/_app/ai/receptionist'
      path: '/ai/receptionist'
      fullPath: '/ai/receptionist'
      preLoaderRoute: typeof AppAiReceptionistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/copilot': {
      id: '/_app/ai/copilot'
      path: '/ai/copilot'
      fullPath: '/ai/copilot'
      preLoaderRoute: typeof AppAiCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/care': {
      id: '/_app/ai/care'
      path: '/ai/care'
      fullPath: '/ai/care'
      preLoaderRoute: typeof AppAiCareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/super': {
      id: '/_app/admin/super'
      path: '/admin/super'
      fullPath: '/admin/super'
      preLoaderRoute: typeof AppAdminSuperRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/org': {
      id: '/_app/admin/org'
      path: '/admin/org'
      fullPath: '/admin/org'
      preLoaderRoute: typeof AppAdminOrgRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/features': {
      id: '/_app/admin/features'
      path: '/admin/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AppAdminFeaturesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/clinic': {
      id: '/_app/admin/clinic'
      path: '/admin/clinic'
      fullPath: '/admin/clinic'
      preLoaderRoute: typeof AppAdminClinicRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppClinicsRoute: typeof AppClinicsRoute
  AppDoctorRoute: typeof AppDoctorRoute
  AppEmrRoute: typeof AppEmrRoute
  AppLabRoute: typeof AppLabRoute
  AppPatientRoute: typeof AppPatientRoute
  AppPatientOnboardingRoute: typeof AppPatientOnboardingRoute
  AppPatientWidgetRoute: typeof AppPatientWidgetRoute
  AppPharmacyRoute: typeof AppPharmacyRoute
  AppRbacRoute: typeof AppRbacRoute
  AppReceptionRoute: typeof AppReceptionRoute
  AppSubscriptionsRoute: typeof AppSubscriptionsRoute
  AppTelemedicineRoute: typeof AppTelemedicineRoute
  AppWhitelabelRoute: typeof AppWhitelabelRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminClinicRoute: typeof AppAdminClinicRoute
  AppAdminFeaturesRoute: typeof AppAdminFeaturesRoute
  AppAdminOrgRoute: typeof AppAdminOrgRoute
  AppAdminSuperRoute: typeof AppAdminSuperRoute
  AppAiCareRoute: typeof AppAiCareRoute
  AppAiCopilotRoute: typeof AppAiCopilotRoute
  AppAiReceptionistRoute: typeof AppAiReceptionistRoute
  AppAiReportsRoute: typeof AppAiReportsRoute
  AppAiRiskRoute: typeof AppAiRiskRoute
  AppAiScribeRoute: typeof AppAiScribeRoute
  AppPatientProfilePatientIdRoute: typeof AppPatientProfilePatientIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppBillingRoute: AppBillingRoute,
  AppClinicsRoute: AppClinicsRoute,
  AppDoctorRoute: AppDoctorRoute,
  AppEmrRoute: AppEmrRoute,
  AppLabRoute: AppLabRoute,
  AppPatientRoute: AppPatientRoute,
  AppPatientOnboardingRoute: AppPatientOnboardingRoute,
  AppPatientWidgetRoute: AppPatientWidgetRoute,
  AppPharmacyRoute: AppPharmacyRoute,
  AppRbacRoute: AppRbacRoute,
  AppReceptionRoute: AppReceptionRoute,
  AppSubscriptionsRoute: AppSubscriptionsRoute,
  AppTelemedicineRoute: AppTelemedicineRoute,
  AppWhitelabelRoute: AppWhitelabelRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminClinicRoute: AppAdminClinicRoute,
  AppAdminFeaturesRoute: AppAdminFeaturesRoute,
  AppAdminOrgRoute: AppAdminOrgRoute,
  AppAdminSuperRoute: AppAdminSuperRoute,
  AppAiCareRoute: AppAiCareRoute,
  AppAiCopilotRoute: AppAiCopilotRoute,
  AppAiReceptionistRoute: AppAiReceptionistRoute,
  AppAiReportsRoute: AppAiReportsRoute,
  AppAiRiskRoute: AppAiRiskRoute,
  AppAiScribeRoute: AppAiScribeRoute,
  AppPatientProfilePatientIdRoute: AppPatientProfilePatientIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
